### PR TITLE
Add pep8 test

### PR DESCRIPTION
**Pull request by EmilyBourne**

### CODE REVIEW

**Comment by dominikbell** [comment]
Now all the files have been formatted, i.e. also in `pygyro/initialisation/pythran_initialiser_funcs.py` the `#pythran` has been changed to `# pythran`

**Comment by dominikbell** [comment]
In `pygyro/advection/numba_accelerated_advection_steps.py` the commands
```
import sys
sys.path.insert(0, '..')
```
have been deleted. Why? does this still work then?

**Comment by EmilyBourne** [comment]
> Now all the files have been formatted, i.e. also in `pygyro/initialisation/pythran_initialiser_funcs.py` the `#pythran` has been changed to `# pythran`

See https://github.com/pyccel/pygyro/pull/15#discussion_r930725738

**Comment by EmilyBourne** [comment]
> In `pygyro/advection/numba_accelerated_advection_steps.py` the commands
> 
> ```
> import sys
> sys.path.insert(0, '..')
> ```
> 
> have been deleted. Why? does this still work then?

See https://github.com/dominikbell/pygyro/pull/13/commits/b6712a74a650a5981cda1adebb7a10c7b28df00e . I am now managing this more cleanly in the makefile. As you can see the numba test is still passing

**Comment by dominikbell** [comment]
Great, please rebase and then I can merge.

**Pull request merged**
